stages:
  - remote_setup
  - test
  - code_analysis
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # https://pre-commit.com/#gitlab-ci-example  (TODO: caching does not work for pre-commit)
  PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"

cache:
  paths:
    - .cache/pip
    - ${PRE_COMMIT_HOME}
    - venv/

setup:
  stage: remote_setup
  script:
    - virtualenv venv -p ~/Python-3.7.9/python
    - source venv/bin/activate
    - python -V
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade setuptools
    - python -m pip install --upgrade twine
    - python -m pip install -r requirements-dev.txt

unittests:
  stage: test
  before_script:
    - source venv/bin/activate
    - python -V
  script:
    - nosetests --with-coverage --cover-erase --cover-inclusive --cover-package=datafold/ --cover-html --cover-html-dir="./coverage/" datafold/ -v
  allow_failure: false
  artifacts:
    paths:
      - ./coverage/
    expire_in: 1 week
    when: on_success

functional_tests:
  before_script:
    - source venv/bin/activate
    - python -V
  script:
    - export PYTHONPATH=`pwd`
    - echo $PYTHONPATH
    - nosetests tutorials/ -v

code_checks:
  stage: code_analysis
  before_script:
    - source venv/bin/activate
    - python -V
  script:
    - pre-commit run --all
  allow_failure: true

docu_check:
  stage: code_analysis
  before_script:
    - source venv/bin/activate
    - python -V
  script:
    - cd doc/ && make html
  except:
    - master
  allow_failure: false

pages:
  stage: deploy
  before_script:
    - source venv/bin/activate
    - python -V
  script:
    - export DATAFOLD_NBSPHINX_EXECUTE=always
    - sphinx-apidoc -f -o ./doc/source/_apidoc/ ./datafold/
    - sphinx-build -b html ./doc/source/ ./public/
  artifacts:
    paths:
    - public
  only:
    - master

# requires to set TWINE_USERNAME and TWINE_PASSWORD in gitlab CI/CD variables
pypi_upload:
  stage: deploy
  before_script:
    - source venv/bin/activate
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - master
  when: manual