repos:

-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
    -   id: isort

-   repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
    - id: nbstripout
      files: ".ipynb"
