repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
        exclude: .ipynb
#    -   id: check-added-large-files
#        args: [ "--maxkb=500" ]
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: check-toml

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [ --py38-plus ]

-   repo: https://github.com/python/black
    rev: 23.1.0
    hooks:
    - id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort

-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    - id: nbstripout
      files: ".ipynb"
      args: [--drop-empty-cells]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  -   id: flake8

#-   repo: https://github.com/myint/rstcheck
#    rev: v3.3.1
#    hooks:
#    -   id: rstcheck

# applies code formatting on Jupyter notebooks:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.7.0
  hooks:
    - id: nbqa-isort
      additional_dependencies: [ isort==5.12.0 ]
      args: [ --nbqa-mutate ]
    - id: nbqa-black
      additional_dependencies: [black==23.1.0]
      args: [ --nbqa-mutate ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --no-implicit-optional]

# TODO: install
#-   repo: https://github.com/fsfe/reuse-tool
#    rev: v1.1.2
#    hooks:
#      - id: reuse

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
        types: [text]  # overwrite types: [rst]
        types_or: [python, rst]
      - id: rst-inline-touching-normal
        types: [text]  # overwrite types: [rst]
        types_or: [python, rst]

-   repo: local
    hooks:
    -   id: bibliography
        name: bibliography
        entry: python doc/source/verify_bibliography.py
        language: system
        always_run: true
        pass_filenames: false

# Style checker for sphinx (or other) rst documentation.
#-   repo: https://github.com/pycqa/doc8
#    rev: 0.11.1
#    hooks:
#    -   id: doc8
