repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: check-toml

-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    - id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    - id: isort

-   repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
    - id: nbstripout
      files: ".ipynb"

# applies some formatting on Jupyter notebooks too
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.7.0
  hooks:
    - id: nbqa-isort
      additional_dependencies: [ isort==5.8.0 ]
      args: [ --nbqa-mutate ]
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
      args: [ --nbqa-mutate ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --no-implicit-optional]
