repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: check-toml

-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
    -   id: isort

-   repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
    - id: nbstripout
      files: ".ipynb"

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --no-implicit-optional]
