repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: check-toml

-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    - id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort

-   repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
    - id: nbstripout
      files: ".ipynb"

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  -   id: flake8

#-   repo: https://github.com/myint/rstcheck
#    rev: v3.3.1
#    hooks:
#    -   id: rstcheck

# applies some formatting on Jupyter notebooks too
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.7.0
  hooks:
    - id: nbqa-isort
      additional_dependencies: [ isort==5.10.1 ]
      args: [ --nbqa-mutate ]
    - id: nbqa-black
      additional_dependencies: [black==22.3.0]
      args: [ --nbqa-mutate ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --no-implicit-optional]

-   repo: local
    hooks:
    -   id: bibliography
        name: bibliography
        entry: python doc/source/verify_bibliography.py
        language: system
        always_run: true
        pass_filenames: false
